language: node_js
node_js:
  - "13.12.0"
before_install: cd ./ExampleAngularTravis
cache:
  directories:
     - ./ExampleAngularTravis/node_modules
install:
  - npm install
script:
  - npm run-script build
